" Name:          vimrc
" By:	           cyancat
" Tag Added:     22/11/2021
" Desciption:    my vimrc config file


" Things that only work with vim, not neovim
	if !has('nvim')
		set viminfo+=n~/.vim/viminfo
		" From 'General'
		set ttymouse=
	endif

" NOTES, :echo getcompletion('SEARCH', 'filetype')

" Plug Load 
	if empty(glob('~/.vim/autoload/plug.vim'))
		silent !curl -fLo ~\.vim\autoload\plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
		autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
	endif  

" Plug List
	call plug#begin('~/.vim/plugged')
		Plug 'flazz/vim-colorschemes'
		Plug 'vim-airline/vim-airline'
		Plug 'vim-airline/vim-airline-themes'
		Plug 'junegunn/limelight.vim'
		Plug 'junegunn/goyo.vim'
		"Lang
		Plug 'pangloss/vim-javascript'
		Plug 'alvan/vim-closetag'
	call plug#end()

" Plug Settings
	" Colourscheme
	color louver
	let g:airline_theme='silver'
	" Goyo
	filetype detect
	if (&ft=='markdown' || &ft=='text')
		set textwidth=50
		nnoremap :q :qa
		autocmd VimEnter * :Goyo 50x70%
	endif
	" Limelight
	autocmd! User GoyoEnter Limelight
	autocmd! User GoyoLeave Limelight!
	"Closetag Extensions
	let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.php'

" Explore if no file is passed
	if argc() == 0 && !exists("s:std_in")
		autocmd vimenter * Explore 
	endif
	
" General
	syntax on 
	set noswapfile
	set laststatus=2
	set encoding=utf-8
	set fileencoding=utf-8
	set fileencodings=utf-8
	set ttyfast
	set title
	set wildmenu
	set nostartofline
	set shortmess=atI
	set history=1000
	set lazyredraw
	set noshowmatch
	set belloff=all
	set mouse=
	" Auto Comment Insertion, Off
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Wrapping and Line Breaks
	set breakindent
	set wrap
	set linebreak
	set nolist  
	set scrolloff=13
	set textwidth=80
	set formatoptions-=t0
	set formatoptions-=t

" Shifting
	set shiftround
	set autoindent
	set smartindent 
	set cpoptions  +=I

" Number Stuff
	set number 
	set relativenumber

" Search
	set showmatch
	set hlsearch
	set ic
	set incsearch

" Visual Mode 
	vnoremap <c-v> <c-q>" Tab

" Tab Tab Tab
	set tabstop=2 softtabstop=0 noexpandtab shiftwidth=2 smarttab
	"Useful Visual Tab
	vnoremap <tab> >vgv
	vnoremap <s-tab> <vgv

" Make hjkl Graphical
	nnoremap j gj
	nnoremap k gk
	vnoremap j gj
	vnoremap k gk

" 'd' Deletes, Doesn't Cut
	nnoremap d "_d
	vnoremap d "_d

" Split Nav
	nnoremap <c-j> <C-W><C-J>
	nnoremap <c-k> <C-W><C-K>
	nnoremap <c-l> <C-W><C-L>
	nnoremap <c-h> <C-W><C-H>

" Removing h and l, for... (trying this out)
	":nnoremap h b
	":nnoremap l w

" Go
	nnoremap <c-b> :!go run % <cr>

" Include desc.vim
	source ~/.vim/desc.vim

